### ISSUE TITLE
recent_commits_truncated is not handled

### ISSUE THREAD

**Issue by benesch** [kohler/peteramati#13]
When the grading commit is too old (more than 100 commits in the past), peteramati happily discards the grading commit, condemning the line notes of the graded commit to obscurity forever.

Not urgent; I bumped the recent commit limit to 500 for 161.

**Comment by kohler** [comment]
Ugh!

**Comment by kohler** [comment]
This no longer happens :)

**Comment by benesch** [comment]
🙌🏽
