### ISSUE TITLE
No longer possible to set grading commit

### ISSUE THREAD

**Issue by benesch** [kohler/peteramati#3]
This commit seems to have removed the "Grade" button to set the grading commit!

 > https://github.com/kohler/peteramati/commit/97807efae4a8e026f6e4155a06d5ec9e271b9f81#diff-dcc2abeefe7b4696c2731ea1d4d60f83L663

Did this functionality move elsewhere?

**Comment by kohler** [comment]
Restored in fc6fb89

**Comment by benesch** [comment]
This made my night
